In [1]:
from PIL import Image
import tensorflow as tf

C:\Users\HP\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\HP\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\HP\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\HP\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1)

In [2]:
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np

from keras.preprocessing import image

Using TensorFlow backend.


In [3]:
model = load_model('facefeatures_new_model2.h5')

# Loading the cascades
face_cascade = cv2.CascadeClassifier('Haarcascades\haarcascade_frontalface_default.xml')


In [4]:
def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

In [ ]:
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = img_array.astype('float32')
        img_array /= 255.0
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][2]>0.80):
            name='Sanatan'
            #cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
        
        elif(pred[0][1]>0.80):
            name='pathak'
        
        elif(pred[0][0]>0.80):
            name='Bhakat'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

[[0.00596488 0.00454275 0.9894924 ]]
[[0.0045775  0.01658704 0.97883546]]
[[0.00490228 0.01101028 0.9840874 ]]
[[0.00916895 0.01095673 0.9798743 ]]
[[0.02894258 0.019135   0.9519224 ]]
[[0.00444481 0.00754268 0.98801255]]
[[5.5561616e-04 4.3532094e-03 9.9509120e-01]]
[[5.2723195e-04 8.0444233e-04 9.9866831e-01]]
[[4.5886048e-04 1.6814083e-03 9.9785978e-01]]
[[7.5409969e-04 2.0521637e-03 9.9719369e-01]]
[[0.01059458 0.08266225 0.9067431 ]]
[[0.01789778 0.18034469 0.8017576 ]]
[[0.00472066 0.03611877 0.95916057]]
[[0.0115839  0.10367887 0.88473725]]
[[0.00338765 0.02746502 0.9691473 ]]
[[0.00260405 0.01891747 0.97847855]]
[[0.00223286 0.03239795 0.96536916]]
[[0.0231407  0.25443265 0.72242665]]
[[0.0082792  0.05281523 0.9389056 ]]
[[0.00235571 0.02446697 0.9731774 ]]
[[0.00106239 0.00917353 0.9897641 ]]
[[0.00220702 0.01651821 0.9812748 ]]
[[0.0026147  0.01022734 0.987158  ]]
[[0.00134022 0.00841776 0.99024206]]
[[0.00164025 0.00566518 0.9926946 ]]
[[0.00483195 0.02782461 0.96734345]]
[[

[[9.6170139e-04 4.1784402e-03 9.9485993e-01]]
[[5.4280070e-04 2.8409087e-03 9.9661630e-01]]
[[0.00120762 0.00311996 0.99567246]]
[[0.00170393 0.00412058 0.9941755 ]]
[[6.2647538e-04 2.7690176e-03 9.9660444e-01]]
[[0.00105901 0.0044571  0.9944839 ]]
[[5.3655216e-04 5.1918817e-03 9.9427164e-01]]
[[7.5924274e-04 4.0880148e-03 9.9515271e-01]]
[[0.00245802 0.00474467 0.9927973 ]]
[[0.00108168 0.01324551 0.98567283]]
[[7.8318850e-04 4.7264937e-03 9.9449027e-01]]
[[0.00125481 0.00106677 0.99767846]]
[[0.00148491 0.00309646 0.99541867]]
[[0.00113306 0.00305986 0.99580705]]
[[4.8727021e-04 1.8350092e-03 9.9767774e-01]]
[[0.00116602 0.00637108 0.9924629 ]]
[[7.2143704e-04 2.7345489e-03 9.9654406e-01]]
[[7.0416613e-04 1.4449075e-03 9.9785089e-01]]
[[0.00132776 0.00455689 0.99411535]]
[[7.8686362e-04 4.7078039e-03 9.9450535e-01]]
[[0.00132598 0.00769795 0.99097615]]
[[8.8432344e-04 2.4406491e-03 9.9667501e-01]]
[[7.7782397e-04 1.1699774e-03 9.9805224e-01]]
[[3.4439462e-04 4.0129889e-03 9.9564266e-

[[4.5221930e-04 3.7909348e-03 9.9575680e-01]]
[[6.1676867e-04 9.8618725e-03 9.8952138e-01]]
[[0.00117256 0.02341919 0.9754083 ]]
[[8.130328e-04 2.050538e-02 9.786816e-01]]
[[0.00180244 0.02065212 0.97754544]]
[[4.5410308e-04 7.4110860e-03 9.9213481e-01]]
[[0.00115174 0.02718012 0.9716681 ]]
[[6.636037e-04 1.742743e-02 9.819089e-01]]
[[9.3859911e-04 1.8112086e-02 9.8094934e-01]]
[[8.620876e-04 9.899855e-03 9.892380e-01]]
[[0.0019145  0.01082221 0.98726326]]
[[6.3904474e-04 3.0531795e-03 9.9630785e-01]]
[[2.7067770e-04 1.6826399e-03 9.9804664e-01]]
[[0.00100147 0.00446189 0.99453664]]
[[9.7011367e-04 3.4279039e-03 9.9560201e-01]]
[[4.5674189e-04 3.7469624e-03 9.9579632e-01]]
[[0.00212441 0.005254   0.99262154]]
[[2.4509203e-04 2.5905883e-03 9.9716431e-01]]
[[0.00190486 0.01962953 0.9784656 ]]
[[3.5246616e-04 1.3507299e-02 9.8614025e-01]]
[[8.7685173e-04 1.4046804e-02 9.8507637e-01]]
[[0.00116332 0.0108258  0.98801094]]
[[0.00114468 0.01874871 0.9801066 ]]
[[8.5239933e-04 7.3678773e-03 9.